$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json

name: used-cars-train-env  # Provide the name for the environment
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: ../../../data-science/environment/train-conda.yml
description: Environment created from a Docker image plus Conda environment that ensures seamless integration of data-driven pricing decisions, adaptability to changing market conditions, and operational efficiency# Provide the name for the environment
